name: Question
description: Further information is requested
title: '[QUESTION] <title>'
labels: ['question']

body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Outline your question in a clear and concise manner
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What part of the application does this relate to?
      options:
        - Setup and Deployment
        - Configuration
        - App Usage
        - Development
        - Documentation
        - Language Support
    validations:
      required: true
